<?php
require_once 'PHPUnit/Framework.php';

/**
 * Test class for iform.
 * Generated by PHPUnit on 2009-09-15 at 14:37:18.
 */
class iformTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    iform
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new iform;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }
}
?>
